package jlox;

/*
 * Represents a single token generated by the scanner.
 * Each token holds its type, lexeme, literal value, 
 * and line number where it appeared in the source code.
 */
class Token {
	final TokenType type;
	final String lexeme;
	final Object literal;
	final int line;
	
	Token(TokenType type, String lexeme, Object literal, int line) {
		this.type = type;
		this.lexeme = lexeme;
		this.literal = literal;
		this.line = line;
	}
	
	public String toString() {
		return type + " " + lexeme + " " + literal;
	}
}